FROM python:3.11.7-slim

WORKDIR /code

COPY ./config.py /code/config.py
COPY ./db.py /code/db.py
COPY ./main.py /code/main.py
COPY ./requirements.txt /code/requirements.txt

RUN pip3 install --no-cache-dir --upgrade -r /code/requirements.txt

ARG USERNAME=glawkfitty
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN chown -R 1000:1000 /code

USER $USERNAME

CMD ["python3", "./main.py"]

# How does docker work with no credential issues on ec2?? locally it needs the .aws file.